version: '3'
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:bionic
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Edmonton
    volumes:
      - /media/data/programs/jellyfin/config:/config
      - /media/tv:/data/tvshows
      - /media/data/movies:/data/movies
      - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/vcsm:/dev/vcsm #optional
      - /dev/vchiq:/dev/vchiq #optional
      - /dev/video10:/dev/video10 #optional
      - /dev/video11:/dev/video11 #optional
      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped

  couchpotato:
    image: ghcr.io/linuxserver/couchpotato
    container_name: couchpotato
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Edmonton
      - UMASK_SET=022
    volumes:
      - /media/data/programs/couchpotato/config:/config
      - /media/data/downloads:/downloads
      - /media/data/movies:/movies
    ports:
      - 5050:5050
    restart: unless-stopped

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Edmonton
    volumes:
      - /media/data/programs/sabnzbd/config:/config
      - /media/data/downloads:/downloads
      - /media/data/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Edmonton
      - UMASK_SET=022 #optional
    volumes:
      - /media/data/programs/sonarr/config:/config
      - /media/tv:/tv
      - /media/data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
